//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FW.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int IdCompany { get; set; }
        public string Name { get; set; }
        public string TradingName { get; set; }
    }
}
