//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FW.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdxIBMWatsonToneAnalyzer
    {
        public int IdFeedPos { get; set; }
        public Nullable<decimal> IdxAnger { get; set; }
        public Nullable<decimal> IdxDisgust { get; set; }
        public Nullable<decimal> IdxFear { get; set; }
        public Nullable<decimal> IdxJoy { get; set; }
        public Nullable<decimal> IdxSadness { get; set; }
        public Nullable<decimal> IdxAnalytical { get; set; }
        public Nullable<decimal> IdxConfident { get; set; }
        public Nullable<decimal> IdxTentative { get; set; }
        public Nullable<decimal> IdxOpenness { get; set; }
        public Nullable<decimal> IdxConscientiousness { get; set; }
        public Nullable<decimal> IdxExtraversion { get; set; }
        public Nullable<decimal> IdxAgreeableness { get; set; }
        public Nullable<decimal> IdxEmotionalRange { get; set; }
    }
}
