//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FW.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public string CodCompany { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public Nullable<decimal> Variation { get; set; }
        public Nullable<decimal> VariationP { get; set; }
        public Nullable<int> Volume { get; set; }
    }
}
